# CS 180 MP 1 - Google Classifier

Pascua, Primrose F. 2015146181

Saliba, Martin Thomas D.

### Data Preprocessing
1. Initialize
               a. pandas - pd functions
               b. numpy - numpy functions
               c. csv - import and export csv files
               d. re - regex functions

In [25]:
import pandas as pd
import numpy as np 
import graphviz
import csv
import re

 2. Dropped
                a. App - specs
                b. Unnamed :13 - unkown purpose and nature
                c. Current ver - unnecessary
                d. Last Updated - unnecessary
                e. Rows with NaN values - specs

In [26]:
data = pd.read_csv("googleplaystore.csv", header=0)
data.drop(['App','Unnamed: 13', 'Current Ver', 'Android Ver', 'Last Updated'], axis = 1, inplace=True)
data = data[pd.notnull(data['Rating'])]

3. Adjust
    a. Rating - numerical -> categorized
    b. Size - uniform M, removed units
    c. Installs - removed +, converted to float
    d. Price - removed dollar sign, float
    e. Type - changed from Free -> 1, Paid -> 2, float

In [27]:
copy = data.Rating.copy()
data.Rating = data.Rating.mask(copy>4.5, 'High')
data.Rating = data.Rating.mask((copy<=4.5)&(copy>=4.0), 'Average')
data.Rating = data.Rating.mask(copy<4.0, 'Poor')

In [28]:
data.loc[data['Size'].str.contains('k', na = False), 'Size'] = data.loc[data['Size'].str.contains('k'), 'Size'].str.rstrip('k').astype(float)/1000
data.loc[data['Size'].str.contains('M', na = False), 'Size'] = data.loc[data['Size'].str.contains('M', na = False), 'Size'].str.rstrip('M').astype(float)
data.loc[data['Size'].str.contains('Varies', na = False), 'Size'] = 11.5

In [29]:
data.Installs = data.Installs.map(lambda x: x.lstrip('+-').rstrip('+'))
data.Installs = data.Installs.replace(r'\,','',regex=True)

In [30]:
data.Price = data.Price.replace(r'\$','',regex=True)
data = data[data['Price']!='Everyone']
data.Type = data.Type.replace({'Free':1 , 'Paid':2})
data['Price'] = data['Price'].astype(float)

4. Mapped
    a. Category - 1-33 
    b. Content Rating - 1-6
    c. Genres - 1-48

In [31]:
list(data['Category'].unique())

['ART_AND_DESIGN',
 'AUTO_AND_VEHICLES',
 'BEAUTY',
 'BOOKS_AND_REFERENCE',
 'BUSINESS',
 'COMICS',
 'COMMUNICATION',
 'DATING',
 'EDUCATION',
 'ENTERTAINMENT',
 'EVENTS',
 'FINANCE',
 'FOOD_AND_DRINK',
 'HEALTH_AND_FITNESS',
 'HOUSE_AND_HOME',
 'LIBRARIES_AND_DEMO',
 'LIFESTYLE',
 'GAME',
 'FAMILY',
 'MEDICAL',
 'SOCIAL',
 'SHOPPING',
 'PHOTOGRAPHY',
 'SPORTS',
 'TRAVEL_AND_LOCAL',
 'TOOLS',
 'PERSONALIZATION',
 'PRODUCTIVITY',
 'PARENTING',
 'WEATHER',
 'VIDEO_PLAYERS',
 'NEWS_AND_MAGAZINES',
 'MAPS_AND_NAVIGATION']

In [32]:
temp = list(data['Category'].unique())
data.Category = data.Category.replace(temp,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33])

In [33]:
temp = list(data['Content Rating'].unique())
data['Content Rating'] = data['Content Rating'].replace(temp, [1,2,3,4,5,6])
data.Installs = data.Installs.astype(float)

In [34]:
temp = list(data.Genres.unique())
data.Genres = data.Genres.replace(temp,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48])

5. Saving Cleaned Data

In [35]:
data.to_csv('cleaned.csv')

In [36]:
data

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres
0,1,Average,159,19,10000.0,1,0.0,1,1
1,1,Poor,967,14,500000.0,1,0.0,1,1
2,1,High,87510,8.7,5000000.0,1,0.0,1,1
3,1,Average,215644,25,50000000.0,1,0.0,2,1
4,1,Average,967,2.8,100000.0,1,0.0,1,1
5,1,Average,167,5.6,50000.0,1,0.0,1,1
6,1,Poor,178,19,50000.0,1,0.0,1,1
7,1,Average,36815,29,1000000.0,1,0.0,1,1
8,1,Average,13791,33,1000000.0,1,0.0,1,1
9,1,High,121,3.1,10000.0,1,0.0,1,1
10,1,Average,13880,28,1000000.0,1,0.0,1,1
11,1,Average,8788,12,1000000.0,1,0.0,1,1
12,1,Average,44829,20,10000000.0,1,0.0,2,1
13,1,High,4326,21,100000.0,1,0.0,1,1
14,1,Average,1518,37,100000.0,1,0.0,1,1
15,1,Poor,55,2.7,5000.0,1,0.0,1,1
16,1,High,3632,5.5,500000.0,1,0.0,1,1
17,1,Average,27,17,10000.0,1,0.0,1,1
18,1,Average,194216,39,5000000.0,1,0.0,1,1
19,1,High,224399,31,10000000.0,1,0.0,1,1
20,1,Average,450,14,100000.0,1,0.0,1,1
21,1,Average,654,12,100000.0,1,0.0,1,1
22,1,High,7699,4.2,500000.0,1,0.0,3,1
24,1,High,118,23,50000.0,1,0.0,1,1
25,1,High,192,6,10000.0,1,0.0,1,1
26,1,High,20260,25,500000.0,1,0.0,1,1
27,1,Average,203,6.1,100000.0,1,0.0,1,1
28,1,Poor,136,4.6,10000.0,1,0.0,1,1
29,1,Average,223,4.2,100000.0,1,0.0,1,1
30,1,Average,1120,9.2,100000.0,1,0.0,1,1
...,...,...,...,...,...,...,...,...,...
10795,26,Average,7339,4,100000.0,1,0.0,1,41
10796,26,High,61445,7.8,1000000.0,1,0.0,1,41
10797,17,High,32433,46,1000000.0,1,0.0,1,17
10799,21,High,2036,6.8,100000.0,1,0.0,1,37
10800,26,Average,174,12,5000.0,1,0.0,1,41
10801,19,High,52,19,1000.0,1,0.0,1,9
10802,19,Average,185,28,10000.0,1,0.0,2,10
10803,18,Average,56496,81,1000000.0,1,0.0,2,22
10804,18,Average,5442,17,100000.0,1,0.0,2,21
10805,17,Average,3,15,100.0,1,0.0,1,17
10809,19,High,376223,24,1000000.0,1,0.0,1,23
10810,5,High,19,21,100.0,1,0.0,1,5
10812,19,Average,80,13,1000.0,1,0.0,1,9
10814,19,Average,785,31,50000.0,1,0.0,2,10
10815,4,Average,5775,4.9,500000.0,1,0.0,1,4
10817,26,Average,885,8,100000.0,1,0.0,1,41
10819,4,Poor,52,3.6,5000.0,1,0.0,2,4
10820,19,High,22,8.6,1000.0,1,0.0,2,9
10826,21,Average,88486,11.5,5000000.0,1,0.0,4,37
10827,19,Average,117,13,5000.0,1,0.0,1,9
10828,6,Poor,291,13,10000.0,1,0.0,1,6
10829,4,High,603,7.4,10000.0,1,0.0,1,4
10830,32,Poor,881,2.3,100000.0,1,0.0,1,46
10832,30,Poor,1195,0.582,100000.0,1,0.0,1,45
10833,4,High,44,0.619,1000.0,1,0.0,1,4
10834,19,Average,7,2.6,500.0,1,0.0,1,9
10836,19,Average,38,53,5000.0,1,0.0,1,9
10837,19,High,4,3.6,100.0,1,0.0,1,9
10839,4,Average,114,11.5,1000.0,1,0.0,4,4
10840,17,Average,398307,19,10000000.0,1,0.0,1,17

### Classification
1. Initialize
                a. train_test_split - automatically split 
                b. graphviz - decision tree printing
                c. subprocess - check_call
                d. metrics - scoring
                e. tree - decision tree
                f. PIL - image printing

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
from subprocess import check_call
from sklearn import metrics
from sklearn import tree
from PIL import Image

2. Decision Tree Classifier

In [38]:
clean = pd.read_csv("cleaned.csv")
xHeader = list(data)
xHeader.remove('Rating')
yHeader = ['Rating']

In [ ]:
x = pd.DataFrame(columns=xHeader)
x.Category = clean.Category
x.Reviews = clean.Reviews
x.Size = clean.Size
x.Installs = clean.Installs
x.Type = clean.Type
x.Price = clean.Price
x['Content Rating'] = clean['Content Rating']
x.Genres = clean.Genres

y = pd.DataFrame(columns=yHeader)
y.Rating = clean.Rating

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=450)
dcstr = tree.DecisionTreeClassifier(min_samples_leaf=150,min_samples_split=150, random_state=450)
dcstr = dcstr.fit(x_train, y_train)
y_pred = dcstr.predict(x_test)

Classify

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.6101622544833476

In [ ]:
precision= metrics.precision_score(y_test,y_pred,average='micro')
precision

0.6101622544833476

In [ ]:
recall = metrics.recall_score(y_test,y_pred,average='micro')
recall

0.6101622544833476

In [ ]:
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
confusion_matrix

array([[1171,   65,  140],
       [ 291,  124,   51],
       [ 308,   58,  134]], dtype=int64)

 Decision Tree

In [ ]:
att = list(data)
att.remove('Rating')
with open('decisiontreedata.dot', 'w') as t:
    export_graphviz(dcstr, out_file=t, feature_names=att)
command = ["dot", "-Tpng", 'decisiontreedata.dot', "-o", "decisiontree.png"]
check_call(command)
img = Image.open('decisiontree.png')
img.show()

### Google App Success Classifier

In [ ]:
print("Welcome to Google App Success Classifer!")
reviews = int(input("Enter the number of reviews of your app: "))
if (reviews <= 8823.5):
    installs = int(input("Enter number of installs for your app: "))
    if(installs <= 3000):
        if(installs <= 300):
            final = 'Average'
        else:
            if(reviews <= 44.5):
                genres=int(input("GENRES\n1: 'Art & Design'\n2: 'Auto & Vehicles'\n3: 'Beauty'\n4: 'Books & Reference'\n5: 'Business'\n6: 'Comics'\n7: 'Communication'\n8: 'Dating'\n9: 'Education'\n10: 'Entertainment'\n11: 'Events'\n12: 'Finance'\n13: 'Food & Drink'\n14: 'Health & Fitness'\n15: 'House & Home'\n16: 'Libraries & Demo'\n17: 'Lifestyle'\n18: 'Adventure'\n19: 'Arcade'\n20: 'Casual'\n21: 'Card'\n22: 'Action'\n23: 'Strategy'\n24: 'Puzzle'\n25: 'Sports'\n26: 'Music'\n27: 'Word'\n28: 'Racing'\n 29:'Simulation'\n30: 'Board'\n31: 'Trivia'\n32: 'Role Playing'\n33: 'Educational'\n34: 'Music & Audio'\n35: 'Video Players & Editors'\n36: 'Medical'\n37: 'Social'\n38: 'Shopping'\n39: 'Photography'\n40: 'Travel & Local' \n41: 'Tools'\n42: 'Personalization'\n43: 'Productivity'\n44: 'Parenting'\n45: 'Weather'\n46: 'News & Magazines'\n47: 'Maps & Navigation'\n48: 'Casino'\nEnter the genre of your app:  "))
                if (genres <= 19.5):
                    final = 'Average'
                else:
                    final = 'Poor'
            else:
                final = 'Average'
    else:
        if (reviews<=186.5):
            category = int(input("CATEGORIES\n1: 'ART_AND_DESIGN'\n2: 'AUTO_AND_VEHICLES'\n3: 'BEAUTY'\n4: 'BOOKS_AND_REFERENCE'\n5: 'BUSINESS'\n6: 'COMICS'\n7: 'COMMUNICATION'\n8: 'DATING'\n9: 'EDUCATION'\n10: 'ENTERTAINMENT'\n11: 'EVENTS'\n12: 'FINANCE'\n13: 'FOOD_AND_DRINK'\n14: 'HEALTH_AND_FITNESS'\n15: 'HOUSE_AND_HOME'\n16: 'LIBRARIES_AND_DEMO'\n17: 'LIFESTYLE'\n18: 'GAME'\n19: 'FAMILY'\n20: 'MEDICAL'\n21: 'SOCIAL'\n22: 'SHOPPING'\n23: 'PHOTOGRAPHY'\n24: 'SPORTS'\n25: 'TRAVEL_AND_LOCAL'\n26: 'TOOLS'\n27: 'PERSONALIZATION'\n28: 'PRODUCTIVITY'\n29: 'PARENTING'\n30: 'WEATHER'\n31: 'VIDEO_PLAYERS'\n32: 'NEWS_AND_MAGAZINES'\n33: 'MAPS_AND_NAVIGATION'\nEnter the category of your app:  "))
            if (category<=20.5):
                if(category<=18.5):
                    final = 'Poor'
                else:
                    final = 'High'
            else:
                final = 'Poor'
        else:
            if(installs <= 75000):
                final = 'High'
            else:
                if(reviews<=1487):
                    if(genres <= 16.5):
                        final = 'High'
                    else:
                        final = 'Poor'
                else:
                    final = 'High'
else:
    final = 'High'

print("Google App Success: ",final)

Welcome to Google App Success Classifer!